In [ ]:
import pandas as pd
import csv

sentiment_scores = []
csvfile = "sentiment.csv"
df = pd.read_csv("march20_march21.csv")
#print(df.describe())

sentiment_scores.append(df.iloc[:,1].mean())

#print(sentiment_scores)

for i in range(20,29):
  df = pd.read_csv("march{}_march{}.csv".format(i,i+1))
  print(df.iloc[:,1].mean())
  sentiment_scores.append(df.iloc[:,1].mean())

df = pd.read_csv("march30_march31.csv")
print(df.iloc[:,1].mean())
sentiment_scores.append(df.iloc[:,1].mean())

df = pd.read_csv("march31_april1.csv")
print(df.iloc[:,1].mean())
sentiment_scores.append(df.iloc[:,1].mean())

for i in range(1,30):
  df = pd.read_csv("april{}_april{}.csv".format(i,i+1))
  print(df.iloc[:,1].mean())
  sentiment_scores.append(df.iloc[:,1].mean())

df = pd.read_csv("april30_may1.csv")
print(df.iloc[:,1].mean())
sentiment_scores.append(df.iloc[:,1].mean())

for i in range(1,31):
  df = pd.read_csv("may{}_may{}.csv".format(i,i+1))
  print(df.iloc[:,1].mean())
  sentiment_scores.append(df.iloc[:,1].mean())

df = pd.read_csv("may31_june1.csv")
print(df.iloc[:,1].mean())
sentiment_scores.append(df.iloc[:,1].mean())

for i in range(1,30):
  df = pd.read_csv("june{}_june{}.csv".format(i,i+1))
  print(df.iloc[:,1].mean())
  sentiment_scores.append(df.iloc[:,1].mean())

df = pd.read_csv("june30_july1.csv")
print(df.iloc[:,1].mean())
sentiment_scores.append(df.iloc[:,1].mean())

for i in range(1,19):
  df = pd.read_csv("july{}_july{}.csv".format(i,i+1))
  print(df.iloc[:,1].mean())
  sentiment_scores.append(df.iloc[:,1].mean())

with open(csvfile, "w") as output:
    writer = csv.writer(output, lineterminator='\n')
    for val in sentiment_scores:
        writer.writerow([val])

0.11048981901745508
0.133970286778596
0.12886307893122317
0.13817491859299472
0.1294145066885216
0.11871962185124035
0.11740415799763704
0.13469250867239296
0.13389304536711083
0.14990403587916779
0.12890071668932176
0.11975491763807754
0.14851399962325584
0.13393223671881405
0.04607777147089071
0.10706098852456321
0.11915408702212173
0.11885859186738094
0.12119639014709371
0.1020715795744546
0.1220923373619225
0.09962584617420825
0.15299422940687582
0.10018411134247909
0.08272198466521756
0.09687789957359355
0.10939067553364842
0.11170703888811506
0.10949094855899699
0.11478982073461126
0.10379515973546116
0.07565641170179008
0.11143067745995079
0.11666681353461525
0.1329697780087866
0.15095447649243035
0.1296660274059427
0.13806055718339072
0.11175557496565147
0.11131005925339553
0.12899681706473443
0.13642017646295207
0.12274198560675185
0.12776083784684883
0.1223867802428249
0.12916534557785606
0.11577228728510075
0.12984787991217667
0.12601992992675531
0.13539391759128858
0.16681441855406132
0.11740609483159489
0.09772358263470579
0.13149054022397325
0.11689049644725363
0.12024358144659951
0.13852674810520046
0.12390480057661722
0.12318497335577686
0.12979730591481917
0.11669857841855213
0.11396710937131843
0.11133746822105911
0.12946423158430376
0.14468505689641406
0.15545086079531095
0.14436033628834072
0.11938615643211123
0.11930493006026599
0.12898926341320133
0.13531776352815353
0.10779260927684672
0.12693746269347048
0.10815348425954145
0.11517111831448851
0.11345596723577515
0.13103335996711707
0.13141673120231678
0.13306726221677082
0.13067453546086844
0.1284216676604644
0.14518477399827387
0.12572774843432954
0.1336339211684688
0.13944665359270206
0.14546577661748858
0.14369964257025733
0.13738352588312902
0.1422272837381915
0.137102016462652
0.15413928361660653
0.1553306842385904
0.16371308498836598
0.14534459531001714
0.15083234252182084
0.14619439126364817
0.14235035125771242
0.15164325456237485
0.1220641373591791
0.1405175203936294
0.1451813969850591
0.13403095499537665
0.15624140828240948
0.1341601034986204
0.15339895956891902
0.17476277195136736
0.16621240701953677
0.14016214970500931
0.1415654742027375
0.13862072225213504
0.1271302479145065
0.15408175266339555
0.16051330963159413
0.13997301513052118
0.15339361093984696
0.1486007313901935
0.143429083138132
0.13355275518891452
0.15016561321815167
0.1550310894917268

In [ ]:
import pandas as pd

df = pd.read_csv("ready_march20_march21.csv")

display(df)

                    coordinates  ... user_verified
0            -80.31869,25.67931  ...         False
1           -111.99674,41.07291  ...         False
2       -2.31745115,53.64853756  ...         False
3                -73.8669,40.85  ...         False
4              -96.7977,32.7774  ...         False
...                         ...  ...           ...
1276          -122.3308,47.6046  ...         False
1277              -117.58,33.88  ...         False
1278  -106.69799939,35.11418768  ...         False
1279           -106.489,31.7658  ...         False
1280         -80.07418,26.46437  ...         False

[1281 rows x 34 columns]

       favorite_count            id  ...  user_statuses_count  user_time_zone
count     1281.000000  1.281000e+03  ...         1.281000e+03             0.0
mean         0.830601  1.240974e+18  ...         1.530349e+04             NaN
std          5.371673  1.393586e+14  ...         7.265796e+04             NaN
min          0.000000  1.240728e+18  ...         4.000000e+00             NaN
25%          0.000000  1.240847e+18  ...         9.210000e+02             NaN
50%          0.000000  1.240996e+18  ...         2.927000e+03             NaN
75%          1.000000  1.241093e+18  ...         9.495000e+03             NaN
max        122.000000  1.241208e+18  ...         1.464331e+06             NaN

[8 rows x 13 columns]